laptop:
  hosts:
    xps15:
      ansible_host: localhost
      ansible_user: "{{ xps15_ssh_user }}"
      ansible_password: "{{ xps15_ssh_password }}"
      ansible_become_password: "{{ xps15_pwd }}"
